### ISSUE TITLE
Chainweaver wallet not updated with transaction balances.

### ISSUE THREAD

**Issue by TheRealGreyGhost** [kadena-io/chainweaver#703]
I am getting this error in explorer when writing to chainweaver wallet from KD5 box through poolflare.
ERROR
An unexpected error occured when processing request key: k:b01c5a40355efb38596f4095db6038f7bc3d64d00ed6dafa08fc8c9b2fe6d418
Help us make our tools better by filing an issue with the below message at www.github.com/kadena-io/block-explorer :
"Error in $: Failed reading: not a valid json value"
Sequence of events:
In response to KIP0012.
Based on various recommendations I established a wallet on Chainweaver (Account Name: b01c5a40355efb38596f4095db6038f7bc3d64d00ed6dafa08fc8c9b2fe6d418) using the Chainweaver web access portal (chainweaver.kadena.network) and because of exchange irregularities (Kucoin & Zelcor)
As a test I configured the miner to mine to b01c5a40355efb38596f4095db6038f7bc3d64d00ed6dafa08fc8c9b2fe6d418@stratum+tcp//kda-us-ss.poolflare.com:443 the pool refused the connection.
So assuming that KIP0012 was fully implemented at the pool I switched the pool settings to k:b01c5a40355efb38596f4095db6038f7bc3d64d00ed6dafa08fc8c9b2fe6d418@stratum+tcp//kda-us-ss.poolflare.com:443 the miner connected.
There were two payouts from the miner and one manual transfer from Zelcore

TX_IDs :  https://explorer.chainweb.com/mainnet/txsearch?q=k%3Ab01c5a40355efb38596f4095db6038f7bc3d64d00ed6dafa08fc8c9b2fe6d418

But i see no balance updates in Chainweaver wallet for the above transactions.

**Comment by jmininger** [comment]
So that first error (` An unexpected error occured when processing request key: k:b01c5a40355efb38596f4095db6038f7bc3d64d00ed6dafa08fc8c9b2fe6d418` ) looks like its from the block explorer and not from chainweaver. Its likely because you entered the account name as a request key. Note, its not a friendly error message and we redeployed with a better one earlier today

You can always check balance.chainweb.com with the address `k:b01c5a40355efb38596f4095db6038f7bc3d64d00ed6dafa08fc8c9b2fe6d418` to view the actual balance. It looks like its all there atm

To view the balance in chainweaver, you need to `Add Account` and enter `k:b01c5a40355efb38596f4095db6038f7bc3d64d00ed6dafa08fc8c9b2fe6d418` first. It will not show up as a balance for account: `b01c5a40355efb38596f4095db6038f7bc3d64d00ed6dafa08fc8c9b2fe6d418` since they are two disparate accounts. Also note that you might have to press the `Refresh` button to detect a new balance, since we dont constantly poll the node for "new" txns

**Comment by TheRealGreyGhost** [comment]
Thanks. I did not realize we needed the k: prefix in the chainweaver. I'll get everything collated into the one account and makes sure all of the KDA Accounts are preceded in the same way.
